"""
Audit logging middleware for authentication events.

This middleware logs all authentication-related events to the auth_audit_log table:
- User ID (if authenticated)
- Event type (registration, login, token_refresh, logout, password_change)
- Success status (based on HTTP status code)
- IP address
- User agent
- Timestamp (auto-generated by database)

Story: 1C - API Endpoints & Middleware
Epic: 2 (Authentication & Authorization Foundation)
"""

from fastapi import Request
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import Response

from src.database.session import get_async_session_maker
from src.database.models import AuthAuditLog


class AuditLogMiddleware(BaseHTTPMiddleware):
    """
    Middleware to log all authentication-related events.

    Logs to auth_audit_log table:
    - All requests to /api/auth/* endpoints
    - Includes: user_id, event_type, success, ip_address, user_agent

    Event Types:
        - registration: POST /api/auth/register
        - login: POST /api/auth/token
        - token_refresh: POST /api/auth/refresh
        - logout: POST /api/auth/logout
        - password_change: PUT /api/users/me/password

    Success Determination:
        - 2xx/3xx status codes = success
        - 4xx/5xx status codes = failure

    Security:
        - Runs asynchronously to avoid blocking requests
        - Generic user_id extraction (from request.state.user)
        - Separate database session for logging (isolation)
    """

    async def dispatch(self, request: Request, call_next) -> Response:
        """
        Intercept request, process, and log authentication events.

        Args:
            request: FastAPI Request object
            call_next: Next middleware/endpoint in chain

        Returns:
            Response: HTTP response from endpoint

        Side Effects:
            Writes to auth_audit_log table asynchronously
        """
        # Only audit /api/auth/* and /api/users/me/password endpoints
        if not (
            request.url.path.startswith("/api/auth")
            or request.url.path == "/api/users/me/password"
        ):
            return await call_next(request)

        # Extract request metadata
        ip_address = request.client.host if request.client else "Unknown"
        user_agent = request.headers.get("User-Agent", "Unknown")

        # Process request
        response = await call_next(request)

        # Determine event type and success from path and status
        event_type = self._get_event_type(request.url.path)
        success = 200 <= response.status_code < 400

        # Extract user_id from request state (set by auth middleware if authenticated)
        user_id = getattr(request.state, "user_id", None)

        # Log to database asynchronously (separate session)
        # This prevents audit logging from interfering with request handling
        try:
            session_maker = get_async_session_maker()
            async with session_maker() as db:
                audit_entry = AuthAuditLog(
                    user_id=user_id,
                    event_type=event_type,
                    success=success,
                    ip_address=ip_address,
                    user_agent=user_agent,
                )
                db.add(audit_entry)
                await db.commit()
        except Exception as e:
            # Log error but don't fail the request
            import logging

            logger = logging.getLogger(__name__)
            logger.error(f"Failed to log audit event: {e}")

        return response

    def _get_event_type(self, path: str) -> str:
        """
        Map endpoint path to event type.

        Args:
            path: Request URL path

        Returns:
            Event type string

        Event Type Mapping:
            - /api/auth/register → registration
            - /api/auth/token → login
            - /api/auth/refresh → token_refresh
            - /api/auth/logout → logout
            - /api/users/me/password → password_change
            - Other → unknown
        """
        if "register" in path:
            return "registration"
        elif "token" in path and "refresh" not in path:
            return "login"
        elif "refresh" in path:
            return "token_refresh"
        elif "logout" in path:
            return "logout"
        elif "password" in path:
            return "password_change"
        return "unknown"
