"""Initial schema with tenant_configs and enhancement_history

Revision ID: 63a573401118
Revises: 
Create Date: 2025-11-01 14:10:53.306495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a573401118'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enhancement_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('ticket_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('context_gathered', sa.JSON(), nullable=True),
    sa.Column('llm_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enhancement_history_status'), 'enhancement_history', ['status'], unique=False)
    op.create_index(op.f('ix_enhancement_history_tenant_id'), 'enhancement_history', ['tenant_id'], unique=False)
    op.create_index('ix_enhancement_history_tenant_ticket', 'enhancement_history', ['tenant_id', 'ticket_id'], unique=False)
    op.create_index(op.f('ix_enhancement_history_ticket_id'), 'enhancement_history', ['ticket_id'], unique=False)
    op.create_table('tenant_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('servicedesk_url', sa.String(length=500), nullable=False),
    sa.Column('servicedesk_api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('webhook_signing_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('enhancement_preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_configs_tenant_id'), 'tenant_configs', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_configs_tenant_id'), table_name='tenant_configs')
    op.drop_table('tenant_configs')
    op.drop_index(op.f('ix_enhancement_history_ticket_id'), table_name='enhancement_history')
    op.drop_index('ix_enhancement_history_tenant_ticket', table_name='enhancement_history')
    op.drop_index(op.f('ix_enhancement_history_tenant_id'), table_name='enhancement_history')
    op.drop_index(op.f('ix_enhancement_history_status'), table_name='enhancement_history')
    op.drop_table('enhancement_history')
    # ### end Alembic commands ###
